---
- name: Create Credentials
  hosts: localhost
  vars_files: vars.yml
  tasks:

    - name: Create SCM Credential
      ansible.controller.credential:
        name: "Travis GH PAT Credential"
        description: "Travis Github Token"
        state: present
        organization: DO374_Demo
        credential_type: GitHub Personal Access Token
        inputs:
          token: "{{ Github_PAT }}"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
 
