---
- name: Playbook to Configure Controller with a Project-Based inventory Source for the Job Template Workflow Demo
  hosts: localhost
  tasks:

    - name: Create DO374 Inventory
      awx.awx.inventory:
        name: "DO374 Web Workflow"
        organization: "DO374_Demo"
        state: "present"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com


    - name: Create DO374 Project Inventory -  Source
      awx.awx.inventory_source:
        name: "DO374 Project Inventory"
        organization: "DO374_Demo"
        inventory: "DO374 Web Workflow"
        source_project: "DO374"
        source: scm
        source_path: "Demos/CH3/inventory"
        state: "present"
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
